### ISSUE TITLE
Deprecation warnings with latest Sass

### ISSUE THREAD

**Issue by nertzy** [kostia/jquery-minicolors-rails#15]
We get this output when we precompile our assets.

```
       DEPRECATION WARNING on line 10, column 17 of /tmp/staged/app/vendor/bundle/ruby/2.2.0/gems/jquery-minicolors-rails-2.1.4.0/vendor/assets/stylesheets/jquery.minicolors.css.erb:
       Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
       To include a newline in a string, use "\a" or "\a " as in CSS.
       DEPRECATION WARNING on line 83, column 17 of /tmp/staged/app/vendor/bundle/ruby/2.2.0/gems/jquery-minicolors-rails-2.1.4.0/vendor/assets/stylesheets/jquery.minicolors.css.erb:
       Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
       To include a newline in a string, use "\a" or "\a " as in CSS.
       DEPRECATION WARNING on line 107, column 17 of /tmp/staged/app/vendor/bundle/ruby/2.2.0/gems/jquery-minicolors-rails-2.1.4.0/vendor/assets/stylesheets/jquery.minicolors.css.erb:
       Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
       To include a newline in a string, use "\a" or "\a " as in CSS.
       DEPRECATION WARNING on line 137, column 23 of /tmp/staged/app/vendor/bundle/ruby/2.2.0/gems/jquery-minicolors-rails-2.1.4.0/vendor/assets/stylesheets/jquery.minicolors.css.erb:
       Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
       To include a newline in a string, use "\a" or "\a " as in CSS.
```

**Comment by kostia** [comment]
On it! Thanks for reporting :smile:

**Comment by kostia** [comment]
@nertzy Unfortunately I could not reproduce the problem with several `sass-rails` versions. Could you please provide your `Gemfile`?

**Comment by dilnavaz** [comment]
Change application.sass to application.css.sass. And include mini-colors css as 
/*
 *= require jquery.minicolors
*/.

**Comment by dilnavaz** [comment]
Copy the mini-colors css file into your assets and rename it to sass. Import it inside application.scss. I had this similar issue and now its working.

**Comment by kostia** [comment]
> Copy the mini-colors css file

Which CSS file do you mean?

If you mean [this one](https://github.com/kostia/jquery-minicolors-rails/blob/master/vendor/assets/stylesheets/jquery.minicolors.css.erb): there is normally no need to copy assets from the gems to your application's folder, because it doesn't matter for the asset pipeline where your assets reside and all locations are treated equally. For which use case do you need to copy the CSS file?

**Comment by dilnavaz** [comment]
Hey,
The gem is showing the above depreciation warning with sass. I tried to use an application.css.sass. It removes the depreciation warnings, but the mini-colors is not showing up(everything is working perfect in the chrome inspect element window). I think its an issue with sass not supporting css. So i did the workaround to get it working perfectly. And I know it doesn't matter where the assets are placed. :)

**Comment by dilnavaz** [comment]
Sorry, I didn't meant the css file in your repo. I meant the original jquery-mini-colors css.
https://github.com/claviska/jquery-minicolors/blob/master/jquery.minicolors.css

**Comment by kostia** [comment]
Bundling https://github.com/claviska/jquery-minicolors/blob/master/jquery.minicolors.css is one of the main purposes of this gem. So it should of course produce no warnings. That's why I try to find out the cause of that warnings in order to fix them.

I can not reproduce the warning with the [latest version of the gem `sass-rails`](https://rubygems.org/gems/sass-rails/versions/5.0.3). So back to [my original question](https://github.com/kostia/jquery-minicolors-rails/issues/15#issuecomment-122571402):
> Could you please provide your Gemfile?

**Comment by dilnavaz** [comment]
Actually I am not the one who raised the issue. Anyway I will provide my gem file. :smile: 

	 source 'https://rubygems.org'
         # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
         gem 'rails', '4.2.1'

	gem 'dotenv-rails'

	# Use sqlite3 as the database for Active Record
	gem 'mysql2'
	# Use SCSS for stylesheets
	gem 'sass-rails', '~> 5.0'
	# Use Uglifier as compressor for JavaScript assets
	gem 'uglifier', '>= 1.3.0'
	# Use CoffeeScript for .coffee assets and views
	gem 'coffee-rails', '~> 4.1.0'
	# See https://github.com/rails/execjs#readme for more supported runtimes
	# gem 'therubyracer', platforms: :ruby

	# Use jquery as the JavaScript library
	gem 'jquery-rails'

	gem 'jquery-ui-rails'
	# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
	gem 'turbolinks'
	# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
	gem 'jbuilder', '~> 2.0'
	# bundle exec rake doc:rails generates the API under doc/api.
	gem 'sdoc', '~> 0.4.0', group: :doc


	# Use ActiveModel has_secure_password
	# gem 'bcrypt', '~> 3.1.7'

	# Use Unicorn as the app server
	# gem 'unicorn'

	# Use Capistrano for deployment
	# gem 'capistrano-rails', group: :development

	gem 'bootstrap-sass'

	group :development, :test do
	  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
	  gem 'byebug'

	  # Access an IRB console on exception pages or by using <%= console %> in views
	  gem 'web-console', '~> 2.0'

	  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
	  gem 'spring'
	end

**Comment by kostia** [comment]
@dilnavaz Thanks for providing the `Gemfile`.
Unfortunately with exactly that set gems I still can not reproduce the issue.

My setup:
* A fresh Rails app with the provided `Gemfile` plus `jquery-minicolors-rails`(the latest version).
* `app/assets/stylesheets/colorpicker1.css.sass` loads `jquery.minicolors`.
* `app/assets/stylesheets/colorpicker2.css.scss` loads `jquery.minicolors`.
* `app/assets/stylesheets/application.css` requires `colorpicker1` and `colorpicker2`.

Then I run `bundle exec rake assets:precompile` and see _no_ warnings in the output.

**Comment by dilnavaz** [comment]
Have you tried using application.scss?

**Comment by kostia** [comment]
@dilnavaz Yes, I've tried it different ways:

```scss
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or any plugin's vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any styles
 * defined in the other CSS/SCSS files in this directory. It is generally better to create a new
 * file per style scope.
 *
 *= require jquery.minicolors
 *= require colorpicker1
 *= require colorpicker2
 *= require_tree .
 *= require_self
 */

@import "jquery.minicolors";
```

**Comment by dilnavaz** [comment]
Ok. I will check once again. May be it wasnt a bug.

**Comment by kostia** [comment]
Ok, thanks.

**Comment by dilnavaz** [comment]
Have you tried firing up the server(with application.scss)? Its not showing in pre-compile, but when I fire up my server and send the first request, the warning is still showing.

	DEPRECATION WARNING on line 10, column 17 of /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jquery-minicolors-rails-2.1.4.0/vendor/assets/stylesheets/jquery.minicolors.css.erb:
	Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
	To include a newline in a string, use "\a" or "\a " as in CSS.


	DEPRECATION WARNING on line 83, column 17 of /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jquery-minicolors-rails-2.1.4.0/vendor/assets/stylesheets/jquery.minicolors.css.erb:
	Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
	To include a newline in a string, use "\a" or "\a " as in CSS.


	DEPRECATION WARNING on line 107, column 17 of /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jquery-minicolors-rails-2.1.4.0/vendor/assets/stylesheets/jquery.minicolors.css.erb:
	Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
	To include a newline in a string, use "\a" or "\a " as in CSS.


	DEPRECATION WARNING on line 137, column 23 of /home/dil/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jquery-minicolors-rails-2.1.4.0/vendor/assets/stylesheets/jquery.minicolors.css.erb:
	Unescaped multiline strings are deprecated and will be removed in a future version of Sass.
	To include a newline in a string, use "\a" or "\a " as in CSS.

**Comment by kostia** [comment]
Got it! Thanks for support.

**Comment by dilnavaz** [comment]
You're welcome. :smile:

**Comment by maxwell** [comment]
can you please release a new version of the gem?

Thank you for your hard work, I appreciate it!

**Comment by kostia** [comment]
@maxwell On it! Maybe on weekend.

**Comment by kostia** [comment]
@maxwell https://rubygems.org/gems/jquery-minicolors-rails/versions/2.1.4.1

**Comment by kostia** [comment]
Also please consider to use 2.2.2: https://rubygems.org/gems/jquery-minicolors-rails/versions/2.2.2.0.

**Comment by maxwell** [comment]
Thank you! I will try it and let you know if I have any issues.

Thanks again for working on this, I appreciate it!

On Mon, Jan 11, 2016 at 1:49 PM, Kostiantyn Kahanskyi <
notifications@github.com> wrote:

> Also please consider to use 2.2.2:
> https://rubygems.org/gems/jquery-minicolors-rails/versions/2.2.2.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kostia/jquery-minicolors-rails/issues/15#issuecomment-170701671>
> .
>



-- 
maxwell salzberg - BackerKit, founder
skype: max.salzberg
p: (203) 451-3600
email: maxwell@backerkit.com
twitter: @maxwellsalz
