### ISSUE TITLE
Error with rails 5.1, jquery-rails 4.3.1

### ISSUE THREAD

**Issue by joel1di1** [kostia/jquery-minicolors-rails#26]
Hi,

Error is raised from the file "jquery.minicolors.simple_form.js"
at line > input.minicolors(input.data('minicolors'));
error message : "Uncaught TypeError: input.minicolors is not a function"

My configuration is :
 rails (5.1.3)
 simple_form (3.5.0)
 jquery-minicolors-rails (2.2.3.1)
 jquery-rails (4.3.1)

application.js :
```
//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//= require jquery.minicolors
//= require jquery.minicolors.simple_form
//= require turbolinks
//= require bootstrap
//= require_tree .
```

And when I open a console,
```
> $.minicolors
< undefined

```
```
> jQuery
< ƒ ( selector, context ) {

		// The jQuery object is actually just the init constructor 'enhanced'
		// Need init if jQuery is called (just allow error to be thrown if not included)
		return new jQuery…

```

```
> $
< ƒ ( selector, context ) {

		// The jQuery object is actually just the init constructor 'enhanced'
		// Need init if jQuery is called (just allow error to be thrown if not included)
		return new jQuery…
```

**Comment by kostia** [comment]
Hey @joel1di1! 
Thanks for reporting 😄 
Could you please check, if the asset for `jquery.minicolors` is actually requested / loaded by the browser?

**Comment by joel1di1** [comment]
Yes it is.

But I'm on a track, I insert jquery twice : the first from my app, and the second from active_admin.

**Comment by kostia** [comment]
That could be the problem: The second injection would shadow the first one, including all previous extensions to `window.jQuery`.

**Comment by joel1di1** [comment]
Yes, that was it.
Sorry for the false issue.

Regards

**Comment by kostia** [comment]
No problem! 😄

**Comment by fabianoalmeida** [comment]
@kostia I'm facing a similar problem. I'm using SASS. How can I import minicolors to my `application.scss` file? Thanks in advance.

**Comment by fabianoalmeida** [comment]
@kostia Thanks. Solved. 👍
