### ISSUE TITLE
jquery.minicolors.png is referenced but does not exist

### ISSUE THREAD

**Issue by JasonBarnabe** [kostia/jquery-minicolors-rails#29]
jquery.minicolors.png is referenced in https://github.com/kostia/jquery-minicolors-rails/blob/189ff1c84d3232296346626fd5eada280872554a/vendor/assets/stylesheets/jquery.minicolors.css#L10

It was removed in https://github.com/kostia/jquery-minicolors-rails/commit/098c46384e9464667f3d0c419a52cdb085114cde#diff-3ca94b960fed63007f60ad2a67f44136.

**Comment by kostia** [comment]
Hey @JasonBarnabe,

thanks for reporting! It looks to me like the line in question can be safely removed. Would you be so kind to provide a fix PR?
