### ISSUE TITLE
Unable to make this work with Rails 6

### ISSUE THREAD

**Issue by jamesw** [kostia/jquery-minicolors-rails#34]
Added jQuery to the rails app application using yarn
`yarn add jquery`
Added the gem
`gem 'jquery-minicolors-rails'`
bundle install ran fine
Added the following

```
require("jquery")
require("jquery.minicolors")
```
to app/javascript/packs/application.js
Added
` *= require jquery.minicolors`

So that it now looks like this
```
 *= require_tree .
 *= require new_ckeditor/ckeditor.css
 *= require_self
 *= require jquery.minicolors
 */
```
to app/assets/stylesheets/application.scss

Added a field to a form

```
<%= form_with(model: [:admin, theme], local: true) do |form| %>

  <div class="field">
    <%= form.label :header_font_colour %>
    <%= form.text_field :header_font_colour as: :minicolors()%>
  </div>

```
and I am presented with the following error

app/views/admin/themes/_form.html.erb:16: syntax error, unexpected tIDENTIFIER, expecting ')'

**Comment by kostia** [comment]
Well, you have a syntax error in your template at line 16. If you fix it, then the error will go away.

**Comment by jamesw** [comment]
So what exactly is wrong with the syntax?
Neither
`<%= form.text_field :header_font_colour as: :minicolors()%>`
Nor
`<%= form.text_field :header_font_colour as: :minicolors%>`
work
So either the documentation is broken or the gem is broken.

**Comment by kostia** [comment]
It is not valid Erb / Ruby. In both examples you have a syntax error after `:header_font_colour`, because you forgot commas. Additionally, in the first example you have a `()`, which is also invalid Ruby.

**Comment by jamesw** [comment]
OK, thank you for the clarification. No idea how I missed the comma.
