### ISSUE TITLE
Paused on exception Error: Cannot find module 'jquery.minicolors'

### ISSUE THREAD

**Issue by NehaPeer** [kostia/jquery-minicolors-rails#35]
Using 

Ruby  - 2.7.3
Rails - 6.1.3.2

Gem added -

`gem 'jquery-minicolors-rails'`

app/javascript/packs/application.js

```
require("jquery")
require("jquery.minicolors")
```

app/assets/stylesheets/application.scss

`*= require jquery.minicolors`

View page code -
```
<%= f.input :light_background_color, as: :minicolors, input_html: {data: {
          minicolors: {position: :right}}} %>
```

but it throws the below error when we add code in the application.js file- 

Paused on exception
Error: Cannot find module 'jquery.minicolors'

Please give some suggestions.

**Comment by kostia** [comment]
Hey @NehaPeer, thanks for reporting.

You seem to be using [Webpacker](https://guides.rubyonrails.org/webpacker.html). This gem is designed to be used with [the asset pipeline](https://guides.rubyonrails.org/asset_pipeline.html), implemented by [Sprockets](https://github.com/rails/sprockets-rails), as mentioned in both, the Gem and the repository description:
> This gem embeddes the jQuery colorpicker in **_the Rails asset pipeline_**.

**Comment by kostia** [comment]
Closing, since the issue doesn't seem to be valid.
